Redis 44 create docker deployment
EngineersBox/NewsAggregator pull request #6
Opened 2021-04-20 10:37 UTC by EngineersBox

### Changelog

* Added Ansible workflow
* Added Ansible playbook for deploying services
* Fixed SSL issues
* Merged in @RongXin code for rate limiter

2021-04-29 11:38 UTC, WeiXinFam commented on .github/workflows/ansible.yml
> +        run: sudo rm -rf $KEYS_DIR
Not familiar with ansible, but a new line needed?

2021-04-29 11:45 UTC, WeiXinFam requested changes
Overall looks good!

- What's the `flask_logging.conf` for?
- Remove pyc and .idea
- Bunch of endline warnings

2021-05-02 05:09 UTC, EngineersBox commented
the `flask_logging.conf` is used to create loggers for the flask applet, supplying timestamped and threaded entries as well as splitting between stdout and a file.

I'll remove the `pyc` and `.idea` content and fix the endlines

2021-05-02 06:57 UTC, EngineersBox commented
@WeiXinFam I have addressed your comments, have a look when you get a sec

2021-05-04 02:56 UTC, WeiXinFam approved these changes

2021-05-04 02:58 UTC, merged